"""update users table

Revision ID: fad515a96b43
Revises: 15ab8fe84d5b
Create Date: 2025-05-05 16:32:42.942577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fad515a96b43"
down_revision: Union[str, None] = "15ab8fe84d5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    chat_mode_enum = sa.Enum("STRICT", "NEUTRAL", "CASUAL", name="chat_mode_enum")
    chat_mode_enum.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "chat_mode",
            sa.Enum("STRICT", "NEUTRAL", "CASUAL", name="chat_mode_enum"),
            nullable=False,
            server_default="NEUTRAL",
        ),
    )
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.drop_column("users", "chat_mode")
    chat_mode_enum = sa.Enum("STRICT", "NEUTRAL", "CASUAL", name="chat_mode_enum")
    chat_mode_enum.drop(op.get_bind())
    # ### end Alembic commands ###
